/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2022-12-06 08:40:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.example.pojo.*;
import com.example.dao.*;
import java.util.*;

public final class AddStudent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.example.pojo");
    _jspx_imports_packages.add("com.example.dao");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("      \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");




      out.write("\r\n");
      out.write("<form action=\"AddStudentController.jsp\">\r\n");
      out.write("<table border='1'>\r\n");
      out.write("<tr><td>Student ID:</td><td><input type=\"number\" name=\"stuid\"></td></tr>\r\n");
      out.write("<tr><td>First_Name:</td><td><input type=\"text\" name=\"stufname\"></td></tr>\r\n");
      out.write("<tr><td>Last_Name:</td><td><input type=\"text\" name=\"stulname\"></td></tr>\r\n");
      out.write("<tr><td>Date Of Birth:</td><td><input type=\"text\" name=\"studob\"></td></tr>\r\n");
      out.write("<tr><td>Address:</td><td><input type=\"text\" name=\"stuadd\"></td></tr>\r\n");
      out.write("<tr><td>Phone:</td><td><input type=\"number\" name=\"stuphone\"></td></tr>\r\n");
      out.write("<tr><td>Student Class:\r\n");

ClassDAO dao1= new ClassDAO();
List<Classes> li=dao1.display(); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<select name=\"classname\">\r\n");

for(Classes c:li){
	
      out.write("\r\n");
      out.write("	<option value=\"");
      out.print(c.getClass_ID() +","+c.getClass_Name() );
      out.write('"');
      out.write('>');
      out.print(c.getClass_Name() );
      out.write("</option>\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("</select></td></tr>\r\n");
      out.write("<tr><td><input type=\"submit\" value=\"Save Now\"></td></tr>\r\n");
      out.write("</table><br><br>\r\n");
      out.write("<h1>List Of Students</h1>\r\n");
      out.write("<table border='1'>\r\n");
      out.write("<tr><th>Student_ID</th><th>First_Name</th><th>Last_Name</th><th>DOB</th><th>Address</th><th>Phone</th><th>Class_Name</th><th>Edit Action</th><th>Delete Action</th></tr>\r\n");

StudentDAO dao=new StudentDAO();
List<Student> list= dao.display();
for(Student st:list){

      out.write("\r\n");
      out.write("<tr><td>");
      out.print(st.getID() );
      out.write("</td><td>");
      out.print(st.getF_name());
      out.write("</td><td>");
      out.print(st.getL_name());
      out.write("</td><td>");
      out.print(st.getDOB());
      out.write("</td><td>");
      out.print(st.getAddress());
      out.write("</td><td>");
      out.print(st.getPhone());
      out.write("</td><td>");
      out.print(st.getClasses().getClass_Name());
      out.write("</td><td><a href=\"editstudent.jsp?stuid=");
      out.print(st.getID() );
      out.write("\">Edit name</a></td><td><a href=\"deletestudent.jsp?stuid=");
      out.print(st.getID() );
      out.write("\">Delete student</a></td></tr>\r\n");
 } 
      out.write("\r\n");
      out.write("</table><br><br>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
