/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2022-12-06 08:43:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.example.pojo.*;
import com.example.dao.*;
import java.util.*;

public final class classrepo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.example.pojo");
    _jspx_imports_packages.add("com.example.dao");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("         \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
int cid=Integer.parseInt(request.getParameter("cid"));


ClassDAO vf=new ClassDAO();
Classes cc=vf.getClasse(cid);
String name=cc.getClass_Name();


      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1>Class Report of <b>");
      out.print(name );
      out.write("</b></h1>\r\n");
 
AssignDao Dao=new AssignDao();
List<ReportSubjectNTeacher> arr1=Dao.getAllData(cid);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border='1'>\r\n");
      out.write("<tr><th>ID</th><th>Class Name</th><th>Subject Name</th><th>Teacher Name</th></tr>\r\n");

for(ReportSubjectNTeacher cc1:arr1){

      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr><td>");
      out.print(cc1.getId() );
      out.write("</td><td>");
      out.print(cc1.getClassName() );
      out.write("</td><td>");
      out.print(cc1.getSuBName() );
      out.write("</td><td>");
      out.print(cc1.gettName() );
      out.write("</td></tr>\r\n");
} 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<h1>Student List</h1>\r\n");
      out.write("<table border=\"1\">\r\n");
      out.write("<tr><th>Class_ID</th><th>Class_Name</th><th>First_Name</th><th>Last_Name</th><th>DOB</th><th>Address</th><th>Phone</th></tr>\r\n");

StudentDAO dao1=new StudentDAO();
List<Student> list1=dao1.getAllData(cid);
for(Student s:list1){
      out.write("\r\n");
      out.write("	<tr><td>");
      out.print(cid );
      out.write("</td><td>");
      out.print(s.getClasses().getClass_Name() );
      out.write("</td><td>");
      out.print(s.getF_name());
      out.write("</td><td>");
      out.print(s.getL_name() );
      out.write("</td><td>");
      out.print(s.getDOB() );
      out.write("</td><td>");
      out.print(s.getAddress() );
      out.write("</td><td>");
      out.print(s.getPhone() );
      out.write("</td></tr>\r\n");
}
      out.write("\r\n");
      out.write("</table><br><br>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
